<div class="container">
</br>
<div class="form-group">
  <input type="text" class="form-control" id="barrederecherche" placeholder="Rechercher un pousseur">
</div>

    <h1>Slim</h1>
    <div>a microframework for PHP</div>

    <?php if (isset($name)) : ?>
        <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
    <?php else: ?>
    <p>Try <a href="http://www.slimframework.com">SlimFramework</a>
        <?php endif; ?>

</div>


