<div class="container">
	</br>
	<form action="rechercher.phtml">
		<div class="form-group divrecherche">
	  		<input type="text" class="form-control" id="barrederecherche" placeholder="Rechercher un pousseur"><button class="glyphicon glyphicon-search" id="boutonrechercher" type="submit"></button>
		</div>
	</form>

    <h1>Slim</h1>
    <div>a microframework for PHP</div>

    <?php if (isset($name)) : ?>
        <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
    <?php else: ?>
    <p>Try <a href="http://www.slimframework.com">SlimFramework</a>
        <?php endif; ?>

</div>


