<div class="container">


    <?php if (isset($error)) {

            echo '<div class="alert alert-danger" role="alert"> Il y a une erreur, réessayer ou contacter un administrateur !</div>';

    } ?>



    <form method="post" class="formsign" action="/profile/process/" class="form-profile">

        <h2 class="form-profile-heading">Profile</h2>

</br>
        <label>Prénom :</label>
        <input type="text" id="firstname" name="firstname" class="form-control" placeholder="Prénom" required autofocus>
</br>
        <label>Nom :</label>
        <input type="text" id="lastname" name="lastname" class="form-control" placeholder="Nom" required>
</br>
        <label>Adresse :</label>
        <input type="text" id="address" name="address" class="form-control" placeholder="Adresse">
</br>
        <label>Ville :</label>
        <input type="text" id="city" name="city" class="form-control" placeholder="Ville">
</br>
        <label>Téléphone :</label>
        <input type="text" id="phone" name="phone" class="form-control" placeholder="Téléphone">
</br>
        <label>Skype :</label>
        <input type="text" id="skype" name="skype" class="form-control" placeholder="Skype">
</br>
        <label>Note :</label>
        <input type="integer" id="note" name="note" class="form-control" placeholder="Note">
</br>
        <label>Disponibilités :</label>
        <input type="text" id="freetime" name="freetime" class="form-control" placeholder="Disponibilités">
</br>
        </br>

        <button class="btn btn-lg btn-default btn-block" type="submit" id="submit">Enregistrer</button>

    </form>



<!--
    <p class="text-center"><a href="/signin/" class="btn btn-success already">Vous avez déja un compte?</a></p>
-->


</div> <!-- .container -->
