<div class="container">


    <?php if (isset($error)) {

            echo '<div class="alert alert-danger" role="alert"> Il y a une erreur, réessayer ou contacter un administrateur !</div>';

    } ?>


<?php
$db = new dbUsers();
$id = $_SESSION['C2P_ID'];
$profile = array();
$profile['Fullname_User'] = $db->getUserName($id, 'Fullname_User');
$profile['Phonenumber_User'] = $db->getUserName($id, 'Phonenumber_User') or 'Téléphone';
$profile['Skype_User'] = $db->getUserName($id, 'Skype_User') or 'Skype';
$profile['Email_User'] = $db->getUserName($id, 'Email_User') or 'Email';
$profile['Disponibility_User'] = $db->getUserName($id, 'Disponibility_User') or 'Disponibilité';
$res_address = $db->getAddress($id);

if ($res_address['Name_Adresse'] == '')
  $profile['Name_Adresse'] = 'Adresse';
if ($res_address['City_Adresse'] == '')
  $profile['City_Adresse'] = 'Ville';
if ($res_address['CodePostal_Adresse'] == '')
  $profile['CodePostal_Adresse'] = 'Code postal';
?>

    <form method="post" class="formsign" action="/profile/process/" class="form-profile">

    <h2 class="form-profile-heading">Profile</h2>

</br>
        <label>Prénom Nom :</label>
        <input type="text" id="fullname" name="fullname" class="form-control" placeholder="<?php echo $profile['Fullname_User'] ?>" required autofocus>
</br>
        <label>Adresse :</label>
        <input type="text" id="address" name="address" class="form-control" placeholder="<?php echo $profile['Name_Adresse'] ?>">
</br>
        <label>Ville :</label>
        <input type="text" id="city" name="city" class="form-control" placeholder="<?php echo $profile['City_Adresse'] ?>">
</br>
        <label>Téléphone :</label>
        <input type="text" id="phone" name="phone" class="form-control" placeholder="<?php echo $profile['Phonenumber_User'] ?>">
</br>
        <label>Skype :</label>
        <input type="text" id="skype" name="skype" class="form-control" placeholder="<?php echo $profile['Skype_User'] ?>">
</br>
        <label>Disponibilités :</label>
        <input type="text" id="freetime" name="freetime" class="form-control" placeholder="<?php $profile['Disponibility_User'] ?>">
</br>
        <label>Note :</label>
        <input type="integer" id="note" name="note" class="form-control" placeholder="Note...">
</br>
        </br>

        <button class="btn btn-lg btn-default btn-block" type="submit" id="submit">Enregistrer</button>

    </form>



<!--
    <p class="text-center"><a href="/signin/" class="btn btn-success already">Vous avez déja un compte?</a></p>
-->


</div> <!-- .container -->
