<div class="container">
  </br>
  <form action="#">
    <div class="form-group divrecherche">
        <input type="text" class="form-control" id="barrederecherche" placeholder="Rechercher un pousseur"><button class="glyphicon search2 glyphicon-search" id="boutonrechercher" type="submit"></button>
    </div>
  </form>

  Liste des pousseurs.

  <hr>

  <div class="row">
  <?php
  $db = new dbAides();
  $aides = $db->getAides();
  ?>
  </div>

</div>


