<div class="container">
  </br>
  <form action="#">
    <div class="form-group divrecherche">
        <input type="text" class="form-control" id="barrederecherche" placeholder="Rechercher un pousseur"><button class="glyphicon search2 glyphicon-search" id="boutonrechercher" type="submit"></button>
    </div>
  </form>

  Liste des pousseurs.

<?php 

$db = new dbAides(); 
$aides = $db->getAides();
if ($aides)
  foreach ($aides as $aide) {
    echo '
      <tr>
        <td>'.$aide.'</td>
      </tr>';
  }
else
  echo '</br>(vide)';

?>

<?php if (isset($name)) : ?>
  <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
<?php endif; ?>

</div>


