<div class="container">


    <?php if (isset($error)) {

            echo '<div class="alert alert-danger" role="alert"> Il y a une erreur, réessayer ou contacter un administrateur !</div>';

    } ?>



    <form method="post" class="formsign" action="/signup/process/" class="form-signin">

        <h2 class="form-signin-heading">S'inscrire</h2>
        <br>

        <label for="login">Identifiant* :</label>
        <input type="text" id="login" name="login" class="form-control" placeholder="Identifiant" required autofocus>
        <br>

        <label for="password">Mot de passe* :</label>
        <input type="password" id="password" name="password" class="form-control" placeholder="Mot de passe" required>
        <br>

        <label for="fullname">Nom Complet* :</label>
        <input type="text" id="fullname" name="fullname" class="form-control" placeholder="Nom Complet" required>
        <br>

        <label for="email">Email :</label>
        <input type="email" id="email" name="email" class="form-control" placeholder="Adresse mail">

        <br><h5><b>* Champs obligatoires</b></h5>

        <br><br>
        <button class="btn btn-lg btn-default btn-block" type="submit" id="submit">Inscription</button>

    </form>


    </br>
    <p class="text-center"><a href="/signin/" class="btn btn-default already">J'ai déja un compte</a></p>


</div> <!-- .container -->