<div class="container">


    <?php if (isset($error)) {

            echo '<div class="alert alert-danger" role="alert"> Il y a une erreur, réessayer ou contacter un administrateur !</div>';

    } ?>



    <form method="post" class="formsign" action="/signup/process/" class="form-signin">

        <h2 class="form-signin-heading">S'inscrire</h2>
        </br>

        <label>Identifiant :</label>
        <input type="text" id="login" name="login" class="form-control" placeholder="Identifiant" required autofocus>
</br>
        <label>Mot de passe :</label>
        <input type="password" id="password" name="password" class="form-control" placeholder="Mot de passe" required>
</br>
        <label>Email :</label>
        <input type="email" id="email" name="email" class="form-control" placeholder="Adresse mail" required>
</br>
        <label>Prénom :</label>
        <input type="text" id="firstname" name="firstname" class="form-control" placeholder="Prénom" required>
</br>
        <label>Nom :</label>
        <input type="text" id="lastname" name="lastname" class="form-control" placeholder="Nom" required>

        </br>

        </br></br>
        <button class="btn btn-lg btn-default btn-block" type="submit" id="submit">Inscription</button>

    </form>


    </br>
    <p class="text-center"><a href="/signin/" class="btn btn-default already">J'ai déja un compte</a></p>


</div> <!-- .container -->