<div class="container">


    <?php if (isset($error)) {

            echo '<div class="alert alert-danger" role="alert"> Il y a une erreur, réessayer ou contacter un administrateur !</div>';

    } ?>



    <form method="post" class="formsign" action="/signup/process/" class="form-signin">

        <h2 class="form-signin-heading">S'inscrire</h2>
        </br>

        <label>Email :</label>
        <input type="email" id="email" name="email" class="form-control" placeholder="Email address" required autofocus>

        <label>Login :</label>
        <input type="text" id="login" name="login" class="form-control" placeholder="Login" required>

        <label>Mot de passe :</label>
        <input type="password" id="password" name="password" class="form-control" placeholder="Password" required>

        <label>Prénom :</label>
        <input type="text" id="firstname" name="firstname" class="form-control" placeholder="Firstname" required>

        <label>Nom :</label>
        <input type="text" id="lastname" name="lastname" class="form-control" placeholder="Lastname" required>

        <label>Date de naissance :</label>
        <input type="date" id="birthday" name="birthday" class="form-control" required>
        </br>

        <input type="checkbox" value="Rules" required> J'accepte les règles de Coup2Pousse
        </br></br>
        <button class="btn btn-lg btn-primary btn-block" type="submit" id="submit">Inscription</button>

    </form>


    </br>
    <p class="text-center"><a href="/signin/" class="btn btn-success already">J'ai déja un compte?</a></p>


</div> <!-- .container -->